name: FlexiMusic
description: A Music Player App made with Flutter
version: 2.0.0+1
author: Shivam Goyal
homepage: https://shivamgoyal.co
repository: https://github.com/ShivamGoyal1899/FlexiMusic

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fluttery:
  fluttery_audio:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true